#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "
listen 3284-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
	server 164918-web-01 54.146.78.153 check
	server 164918-web-02 54.88.52.22 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
